### ISSUE TITLE
bug: in harfbuzz, isolated vowels do not get a dotted circle when preceded by `&nbsp;`

### ISSUE THREAD

**Issue by mcdurdin** [silnrsi/font-busra#7]
Note how 3 of the 4 are rendering highlighted below are rendering without a dotted circle, despite being isolated, because they are preceded by `&nbsp;` in the html content:

![image](https://github.com/user-attachments/assets/80968fe8-6db0-4cb0-8288-441a1d88a21d)

(Chrome 129.0.6668.59 on Win 11)

![image](https://github.com/user-attachments/assets/4ef85f01-55a3-4e19-8509-5b93f4f3b84a)

**Comment by mcdurdin** [comment]
This looks like it may be related to the character ranges for the Khmer font CSS in the ភាសាខ្មែរ.com website rather than a bug specific to the Khmer Busra font.

Changing from:

```css
@font-face {
  font-family: 'khmer_busra_test';
  unicode-range: U+1780-17FF, U+25CC;
  src: url(Busra-Regular.ttf);
  src: url(Busra-Regular.woff2) format(woff2),
       url(Busra-Regular.woff) format(woff),
       url(Busra-Regular.ttf);
}
```

to:

```css
@font-face {
  font-family: 'khmer_busra_test';
  unicode-range: U+1780-17FF, U+25CC, U+00A0, U+0020;
  src: url(Busra-Regular.ttf);
  src: url(Busra-Regular.woff2) format(woff2),
       url(Busra-Regular.woff) format(woff),
       url(Busra-Regular.ttf);
}
```

resolves the problem (adding space and nbsp to the character ranges to be formatted with the Busra font).
